export default {
  BATCH_ADD_ITEMS_TO_CART: 'BATCH_ADD_ITEMS_TO_CART',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
  UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
  REQUEST_STARTED: 'REQUEST_STARTED',
  REQUEST_FINISHED: 'REQUEST_FINISHED',
};
